## 서블릿 예외 처리 - 오류 화면 제공

서블릿 컨테이너가 제공하는 기본 예외 처리 화면은 고객 친화적이지 않다. 

<br/>

서블릿이 제공하는 오류 화면 기능을 사용해보자

- `response.sendError(404)` : errorPage404 호출
- `response.sendError(500)` : errorPage500 호출
- `RuntimeException` 또는 그 자식 타입의 예외: errorPageEx 호출

<br/>

## 흐름 정리

1. localhost:8080/error-ex url 검색하기.
2. 그러면 ServletExController 컨트롤러로 온다. (밑에 코드 참고)
    
    컨트롤러에서 예외가 발생했다.
    
    ```java
    public class ServletExController {
    
        @GetMapping("/error-ex")
        public void errorEx() {
            throw new RuntimeException("예외 발생");
        }
    
    		```
    ```
<br/>   
    
3. 그러고 이 예외가 was까지 올라간다. 
4. 그런 다음 스프링 부트가 뜰때 다시 밑에 정해둔 `/errorpage/500` 가 있는 컨트롤러로 보낸다.
    
    ```java
    @Component
    public class WebServerCustomizer implements
            WebServerFactoryCustomizer<ConfigurableWebServerFactory> {
    
      @Override
      public void customize(ConfigurableWebServerFactory factory) {
    
    			```
    
         ErrorPage errorPageEx = new ErrorPage(RuntimeException.class, "//error-page/500");
    ```

<br/>

5. ServletExController 컨트롤러로 다시 돌아와 `/errorpage/500` 있는 메서드로 간다.
    
    ```java
        @RequestMapping("/error-page/500")
        public String errorPage500(HttpServletRequest request, 
    		                        HttpServletResponse response) {
    
            log.info("errorPage 500");
            return "error-page/500";
        }
    ```
<br/>    
    
6. 그 다음 html 파일이 있는 `/errorpage/500` 가 오는 것이다.
    
```html

    <!DOCTYPE HTML>
    <html xmlns:th="http://www.thymeleaf.org">
    <head>
        <meta charset="utf-8">
    </head>
    <body>
    <div class="container" style="max-width: 600px">
        <div class="py-5 text-center">
            <h2>500 오류 화면</h2></div>
        <div>
            <p>오류 화면 입니다.</p>
        </div>
        <hr class="my-4">
    </div> <!-- /container -->
    </body>
    </html>
```
    
끝.

<br/>
    
## 핵심 포인트는
    
`throw new RuntimeException("예외 발생");` 과 `response.sendError(404, "404 오류!");` 의 ‘404’ 와
    
`response.sendError(500);` 의 ‘500’ 을 잘 보면 될 것이다.
    
```java
@GetMapping("/error-ex")
public void errorEx() {
        throw new RuntimeException("예외 발생");
}
    
@GetMapping("/error-404")
public void error404(HttpServletResponse response) throws IOException {
            response.sendError(404, "404 오류!");
}
    
@GetMapping("/error-500")
public void error500(HttpServletResponse response) throws IOException {
            response.sendError(500);
}
}

```

<br/>

위에 것들이 전부 밑에 코드 부분에 `HttpStatus.NOT_FOUND`, `INTERNAL_SERVER_ERROR`,
    
`RuntimeException.class` 에 해당 하는 부분들이다. 
    
이 부분 들을 타고 들어가면 안에 404, 500 등등이 있다.
    
```java
    ErrorPage errorPage404 = new ErrorPage(HttpStatus.NOT_FOUND, "/errorpage/404");
    
    ErrorPage errorPage500 = new
                    ErrorPage(HttpStatus.INTERNAL_SERVER_ERROR, "/error-page/500");
    
    ErrorPage errorPageEx = new ErrorPage(RuntimeException.class, "/error-page/500");
    
    factory.addErrorPages(errorPage404, errorPage500, errorPageEx);
 ```

<br/>    

### 만약 localhost:8080/error-page/400 으로 검색한다면?

이렇게 없는 화면이 출력 될 것이다.

![이미지](/programming/img/나31.PNG)

<br/>

## 동작 원리

서블릿은 Exception (예외)가 발생해서 서블릿 밖으로 전달되거나 또는 response.sendError() 가 호출 되었을 때 설정된 오류 페이지를 찾는다.

<br/>

예외 발생 흐름

```
WAS(여기까지 전파) <- 필터 <- 서블릿 <- 인터셉터 <- 컨트롤러(예외발생)
```

<br/>

sendError 흐름

```
WAS(sendError 호출 기록 확인) <- 필터 <- 서블릿 <- 인터셉터 <- 컨트롤러(response.sendError())
```

### WAS는 해당 예외를 처리하는 오류 페이지 정보를 확인한다.

`new ErrorPage(RuntimeException.class, "/error-page/500")`

<br/>

### 중요 포인트 !! was는 다시 오류 페이지를 호출 한다는 것이다.

순서

1. 예를 들어서 `RuntimeException` 예외가 WAS까지 전달되면, 

2. WAS는 오류 페이지 정보를 확인한다.
3. 확인해보니 `RuntimeException` 의 오류 페이지로 `/error-page/500` 이 지정되어 있다. 
4. WAS는 오류 페이지를 출력하기 위해 `/error-page/500` 를 다시 요청한다.


<br/>

오류 페이지 요청 흐름

```
WAS /error-page/500 다시 요청 -> 필터 -> 서블릿 -> 인터셉터 -> 컨트롤러(/error-page/500) -> View
```

<br/>

## 총정리

예외 발생과 오류 페이지 요청 흐름

```
1. WAS(여기까지 전파) <- 필터 <- 서블릿 <- 인터셉터 <- 컨트롤러(예외발생)

2. WAS `/error-page/500` 다시 요청 -> 필터 -> 서블릿 -> 인터셉터 -> 컨트롤러(/errorpage/500) -> View
```

중요한 점은 웹 브라우저(클라이언트)는 서버 내부에서 이런 일이 일어나는지 전혀 모른다는 점이다.

오직 서버 내부에서 오류 페이지를 찾기 위해 추가적인 호출을 한다.

<br/>

정리하면 다음과 같다.

1. 예외가 발생해서 WAS까지 전파된다.

2. WAS는 오류 페이지 경로를 찾아서 내부에서 오류 페이지를 호출한다. 
    
    이때 오류 페이지 경로로 필터, 서블릿, 인터셉터, 컨트롤러가 모두 다시 호출된다.
    
<br/>


## 오류 정보 추가

`request.attribute`에 서버가 담아준 정보

`javax.servlet.error.exception` : 예외

`javax.servlet.error.exception_type` : 예외 타입

`javax.servlet.error.message` : 오류 메시지

`javax.servlet.error.request_uri` : 클라이언트 요청 URI

`javax.servlet.error.servlet_name` : 오류가 발생한 서블릿 이름

`javax.servlet.error.status_code` : HTTP 상태 코드

```java
package hello.exception.servlet;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.util.NestedServletException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@Slf4j
@Controller
public class ErrorPageController {

    //RequestDispatcher 상수로 정의되어 있음
    public static final String ERROR_EXCEPTION = "javax.servlet.error.exception";

    public static final String ERROR_EXCEPTION_TYPE 
															= "javax.servlet.error.exception_type";
    public static final String ERROR_MESSAGE = "javax.servlet.error.message";
    public static final String ERROR_REQUEST_URI = "javax.servlet.error.request_uri";
    public static final String ERROR_SERVLET_NAME = "javax.servlet.error.servlet_name";
    public static final String ERROR_STATUS_CODE = "javax.servlet.error.status_code";

    @RequestMapping("/error-page/404")
    public String errorPage404(HttpServletRequest request, HttpServletResponse response) {

        log.info("errorPage 404");

        printErrorInfo(request);
        return "error-page/404";
    }

    @RequestMapping("/error-page/500")
    public String errorPage500(HttpServletRequest request, HttpServletResponse response) {

        log.info("errorPage 500");

        printErrorInfo(request);
        return "error-page/500";
    }

    private void printErrorInfo(HttpServletRequest request) {
        log.info("ERROR_EXCEPTION: ex=", request.getAttribute(ERROR_EXCEPTION));

        log.info("ERROR_EXCEPTION_TYPE: {}", 
										request.getAttribute(ERROR_EXCEPTION_TYPE));

				//ex의 경우 NestedServletException 스프링이 한번 감싸서 반환
        log.info("ERROR_MESSAGE: {}", request.getAttribute(ERROR_MESSAGE)); 

        log.info("ERROR_REQUEST_URI: {}", request.getAttribute(ERROR_REQUEST_URI));
        log.info("ERROR_SERVLET_NAME: {}", request.getAttribute(ERROR_SERVLET_NAME));
        log.info("ERROR_STATUS_CODE: {}", request.getAttribute(ERROR_STATUS_CODE));
        log.info("dispatchType={}", request.getDispatcherType());
    }
}
```