## 예외 되던지기

예외가 발생한 메서드와 호출한 메서드, 양쪽에서 처리하도록 할 수 있다.

<br/>이것은 예외를 처리한 후에 인위적으로 다시 발생시키는 방법을 통해서 가능한데,

<br/>이것을 예외 되던지기 라고 한다.

<br/>throw문을 사용해서 예외를 다시 발생시킨다.

<br/>다시 발생한 예외는 이 메서드를 호출한 메서드에게 전달되고 호출한 메서드의 try-catch문에서

<br/>예외를 또다시 처리한다

이 방법은 하나의 예외에 대해서 예외가 발생한 메서드와 이를 호출한 메서드 양쪽 모두에서 처리해줘야 <br/>할 작업이 있을 때 사용된다. 이때 주의할 점은 예외가 발생할 메서드에서는 try-catch문을 사용해서 예외처리를 <br/>해줌과 동시에 메서드의 선언부에 발생할 예외를 throws에 지정해줘야 한다는 것이다.

```java
class ExceptionEx17 {
	public static void main(String[] args) 
	{
		try  {
			method1();		
		} catch (Exception e)	{
			System.out.println("main메서드에서 예외가 처리되었습니다.");
		}
	}	// main메서드의 끝

	static void method1() throws Exception {
		try {
			throw new Exception();
		} catch (Exception e) {
			System.out.println("method1메서드에서 예외가 처리되었습니다.");
			throw e;			// 다시 예외를 발생시킨다.
		}
	}	// method1메서드의 끝
}

출력값
method1메서드에서 예외가 처리되었습니다.
main메서드에서 예외가 처리되었습니다.
```


<br/><br/>

>**Reference**
><br/>남궁 성 지음, 『자바의 정석』, 도우출판.
